import { Button } from "@/components/ui/button";
import { Logo } from "@/components/ui/logo";
import { Stethoscope, User, Brain, Heart, Users, Leaf, ArrowRight } from "lucide-react";
import { useNavigate } from "react-router-dom";

const roles = [
  {
    icon: Stethoscope,
    title: "I'm a doctor",
    description: "Manage patients and create personalized diet plans",
    href: "/auth/doctor",
  },
  {
    icon: User,
    title: "I'm a patient",
    description: "Track your diet plan and monitor your wellness journey",
    href: "/auth/patient",
  },
];

const Landing = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: Brain,
      title: "AI-powered diet plans",
      description: "Personalized Ayurvedic nutrition plans generated by advanced AI.",
    },
    {
      icon: Heart,
      title: "Dosha balance tracking",
      description: "Monitor and maintain your Vata, Pitta, and Kapha balance.",
    },
    {
      icon: Users,
      title: "Doctor-patient collaboration",
      description: "Seamless communication between healthcare providers and patients.",
    },
    {
      icon: Leaf,
      title: "Natural wellness",
      description: "A holistic approach combining traditional wisdom with modern technology.",
    },
  ];

  return (
    <div className="relative min-h-screen bg-background">
      {/* Same blush wash the sign-in screen uses, so the first two screens of
          the app feel like one surface. */}
      <div
        className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[600px]"
        style={{
          background:
            "radial-gradient(900px 480px at 50% -10%, hsl(var(--primary) / 0.08) 0%, transparent 65%)",
        }}
      />

      {/* Hero */}
      <section className="mx-auto max-w-5xl px-6 pb-16 pt-16 text-center sm:pt-24">
        <Logo size="lg" className="mx-auto mb-8 shadow-sm" />

        <h1 className="mx-auto max-w-3xl text-title1 sm:text-large-title text-foreground">
          Ayurvedic wellness,
          <br />
          <span className="text-primary">personalized for you</span>
        </h1>

        <p className="mx-auto mt-6 max-w-xl text-body text-foreground-secondary">
          Connect doctors and patients through intelligent, traditional nutrition
          plans built around your unique dosha.
        </p>

        {/* Both role cards get the same accent icon well — the patient card
            used to take a gray one, which read as the disabled option next to
            the doctor's. The "Continue" cue is always visible rather than
            hover-only, since a hover state is invisible on a phone. */}
        <div className="mx-auto mt-12 grid max-w-2xl gap-4 sm:grid-cols-2">
          {roles.map((role) => (
            <button
              key={role.title}
              onClick={() => navigate(role.href)}
              className="group flex h-full flex-col items-start gap-4 rounded-2xl border border-border bg-card p-6 text-left shadow-xs transition-all duration-200 ease-ios hover:border-border-strong hover:shadow-md active:scale-[0.98]"
            >
              <span className="flex h-12 w-12 items-center justify-center rounded-full bg-accent-soft text-primary">
                <role.icon className="h-6 w-6" />
              </span>
              <span className="flex-1">
                <span className="block text-headline text-foreground">{role.title}</span>
                <span className="mt-1 block text-footnote text-foreground-secondary">
                  {role.description}
                </span>
              </span>
              <span className="flex items-center gap-1 text-footnote font-medium text-primary">
                Continue
                <ArrowRight className="h-3.5 w-3.5 transition-transform duration-200 ease-ios group-hover:translate-x-0.5" />
              </span>
            </button>
          ))}
        </div>
      </section>

      {/* Features — a soft blush band. `bg-muted/40` was within a percent of
          the page background, so the section boundary read as an accidental
          hairline rather than a deliberate change of surface. */}
      <section className="border-y border-border bg-accent-soft/50 py-20">
        <div className="mx-auto max-w-5xl px-6">
          <div className="mx-auto mb-12 max-w-xl text-center">
            <h2 className="text-title1 text-foreground">Why choose Prakriva</h2>
            <p className="mt-3 text-body text-foreground-secondary">
              Ancient Ayurvedic wisdom, combined with modern AI, for outcomes you can feel.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="h-full rounded-2xl border border-border bg-card p-6 shadow-xs transition-all duration-200 ease-ios hover:shadow-md"
              >
                <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent-soft text-primary">
                  <feature.icon className="h-5 w-5" />
                </span>
                <h3 className="mt-4 text-headline text-foreground">{feature.title}</h3>
                <p className="mt-1.5 text-footnote text-foreground-secondary">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="mx-auto max-w-2xl px-6 text-center">
          <h2 className="text-title1 text-foreground">Ready to get started?</h2>
          <p className="mt-3 text-body text-foreground-secondary">
            Join the doctors and patients already on their Ayurvedic wellness journey.
          </p>
          <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
            <Button size="lg" onClick={() => navigate("/auth/doctor")}>
              Get started as doctor
            </Button>
            <Button size="lg" variant="outline" onClick={() => navigate("/auth/patient")}>
              Get started as patient
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Landing;
