import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Stethoscope, User, Leaf, Heart, Brain, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import heroImage from "@/assets/ayurveda-hero.jpg";

const Landing = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Diet Plans",
      description: "Personalized Ayurvedic nutrition plans generated by advanced AI"
    },
    {
      icon: Heart,
      title: "Dosha Balance Tracking",
      description: "Monitor and maintain your Vata, Pitta, and Kapha balance"
    },
    {
      icon: Users,
      title: "Doctor-Patient Collaboration",
      description: "Seamless communication between healthcare providers and patients"
    },
    {
      icon: Leaf,
      title: "Natural Wellness",
      description: "Holistic approach combining traditional wisdom with modern technology"
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div 
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: `url(${heroImage})` }}
        >
          <div className="absolute inset-0 bg-gradient-to-r from-background/90 via-background/70 to-transparent" />
        </div>
        
        <div className="relative container mx-auto px-4 py-24 md:py-32">
          <div className="max-w-3xl">
            <h1 className="text-4xl md:text-6xl font-bold text-foreground mb-6 leading-tight">
              
              <span className="bg-gradient-primary bg-clip-text text-transparent"> Prakriva </span>
             
            </h1>
            <p className="text-xl text-muted-foreground mb-12 leading-relaxed">
              Transform your health with personalized Ayurvedic nutrition plans. 
              Connect doctors and patients through intelligent, traditional wellness solutions.
            </p>
            
            <div className="grid md:grid-cols-2 gap-6 max-w-2xl">
              <Card className="card-hover cursor-pointer group" onClick={() => navigate('/auth/doctor')}>
                <CardContent className="p-8 text-center">
                  <div className="bg-gradient-primary w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform">
                    <Stethoscope className="w-8 h-8 text-primary-foreground" />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">I'm a Doctor</h3>
                  <p className="text-muted-foreground">Manage patients and create personalized Ayurvedic diet plans</p>
                </CardContent>
              </Card>
              
              <Card className="card-hover cursor-pointer group" onClick={() => navigate('/auth/patient')}>
                <CardContent className="p-8 text-center">
                  <div className="bg-gradient-secondary w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform">
                    <User className="w-8 h-8 text-secondary-foreground" />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">I'm a Patient</h3>
                  <p className="text-muted-foreground">Track your diet plan and monitor your wellness journey</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              Why Choose Our Platform?
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Combining ancient Ayurvedic wisdom with modern AI technology for optimal health outcomes
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="card-hover">
                <CardContent className="p-6 text-center">
                  <div className="bg-gradient-primary w-12 h-12 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <feature.icon className="w-6 h-6 text-primary-foreground" />
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-muted-foreground text-sm">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-gradient-hero">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Ready to Transform Your Health?
          </h2>
          <p className="text-xl text-white/90 mb-8 max-w-2xl mx-auto">
            Join thousands of healthcare providers and patients who trust our AI-powered Ayurvedic solutions
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg" 
              variant="secondary"
              onClick={() => navigate('/auth/doctor')}
              className="text-lg px-8"
            >
              Get Started as Doctor
            </Button>
            <Button 
              size="lg" 
              variant="outline"
              onClick={() => navigate('/auth/patient')}
              className="text-lg px-8 bg-white/10 border-white/20 text-white hover:bg-white/20"
            >
              Get Started as Patient
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Landing;